GITHUB PIPELINE

Configurando o Git Actions

Observação: Adapte esse código, ou seja, Vão ter nomes diferentes. ADAPTE.
CRIAR A SECRET, com a escrita do chave:
    -> Abra o par de chave no Bloco de Notas
    -> Copie tudo
    -> Coloque dentro da secret

PIPELINE:


# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PipelineFlask

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Teste 
      run: coverage run flask_python.py

    - name: Relatorio do teste
      run: coverage report -m
          
    - name: Deploy no EC2 -AWS
      run: |
            echo "Conectando no EC2"
            echo "${{TESTE_AWS.AWS_KEY_SALAG}}" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-18-215-82-44.compute-1.amazonaws.com "
                  cd Curso do murilo aws\git\flask_python.py/;git pull;./executar.sh"